const categories = [
    "Web Development",
    "App Development",
    "Graphic Design",
    "Artificial Intelligence",
    "Machine Learning",
    "Digital Marketing",
    "SEO (Search Engine Optimization)",
    "Content Writing",
    "Photography",
    "Video Editing",
    "3D Animation",
    "Game Development",
    "Cybersecurity",
    "Blockchain & Cryptocurrency",
    "Data Science",
    "Cloud Computing",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Robotics",
    "Quantum Computing",
    "Business Analytics",
    "Entrepreneurship",
    "Finance & Investing",
    "Economics",
    "Accounting",
    "Project Management",
    "Human Resources (HR) Management",
    "Public Speaking & Communication",
    "Leadership Development",
    "Personal Branding",
    "Sales & Negotiation Skills",
    "Supply Chain Management",
    "Legal Studies",
    "International Relations",
    "Psychology",
    "Philosophy",
    "Creative Writing",
    "Poetry",
    "Music Production",
    "Musical Instrument - Guitar",
    "Cooking & Culinary Arts",
    "Fashion Design",
    "Interior Design",
    "Travel & Tourism Management",
    "Social Media Management",
    "Languages - Spanish",
    "Health & Fitness Coaching",
    "Yoga & Meditation",
    "Nutrition & Dietetics",
    "Gardening & Horticulture",
    "Sustainable Living",
    "Photography & Videography",
  ];
  